# Generated by Django 4.2.3 on 2023-08-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
